version: '2'
services:
  web:
    build: .
    ports:
      - 8080
    volumes:
     - .:/code

  redis:
    image: "redis:alpine"

  balancer:
    image: dockercloud/haproxy
    ports:
      - 81:81
    links:
      - web
    networks:
      - front-tier
      - back-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
